# Generated by Django 2.0.7 on 2019-11-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='postal_or_code',
            new_name='postal_or_zip_code',
        ),
    ]
