# Generated by Django 2.0.7 on 2019-11-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_auto_20191108_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, choices=[('canada', 'Canada'), ('united_states', 'United States')], max_length=120, null=True),
        ),
    ]
