# Generated by Django 2.0.7 on 2019-11-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0006_auto_20191113_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
