# Generated by Django 2.0.7 on 2019-11-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0010_auto_20191113_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
