# Generated by Django 2.0.7 on 2019-11-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0012_address_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
