# Generated by Django 2.0.7 on 2019-11-10 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20191110_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingprofile',
            name='my_email',
        ),
    ]
