# Generated by Django 2.0.7 on 2019-09-17 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintingPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploaded_paintings')),
                ('title', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='paintings.Painting')),
            ],
        ),
    ]
