# Generated by Django 2.0.7 on 2019-09-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0002_paintingphotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintingphotos',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
