# Generated by Django 2.0.7 on 2019-09-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0004_remove_paintingphotos_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintingphotos',
            name='random',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
