# Generated by Django 2.0.7 on 2019-09-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0005_paintingphotos_random'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paintingphotos',
            name='random',
        ),
    ]
