# Generated by Django 2.0.7 on 2019-09-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0006_remove_paintingphotos_random'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='image',
            field=models.ImageField(default='t_and_b_website/media_cdn/default.jpg', upload_to='uploaded_paintings'),
        ),
    ]
