# Generated by Django 2.0.7 on 2019-09-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0007_painting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='uploaded_paintings'),
        ),
    ]
