# Generated by Django 2.0.7 on 2019-09-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0009_auto_20190917_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintingphotos',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='uploaded_paintings'),
        ),
    ]
