# Generated by Django 2.0.7 on 2019-09-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0010_auto_20190917_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintingphotos',
            name='random',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
