# Generated by Django 2.0.7 on 2019-09-17 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0012_remove_paintingphotos_random'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintingphotos',
            name='title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='paintings.Painting'),
        ),
    ]
