# Generated by Django 2.0.7 on 2019-09-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0013_auto_20190917_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='medium',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
