# Generated by Django 2.0.7 on 2019-09-17 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0014_painting_medium'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaintingPhotos',
            new_name='PaintingPhoto',
        ),
    ]
