# Generated by Django 2.0.7 on 2019-09-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0016_auto_20190919_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='series',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
