# Generated by Django 2.0.7 on 2019-09-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0017_painting_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='completed_year',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
