# Generated by Django 2.0.7 on 2019-09-19 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0018_painting_completed_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paintingphoto',
            old_name='photo',
            new_name='src',
        ),
        migrations.AlterField(
            model_name='paintingphoto',
            name='title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='srcs', to='paintings.Painting'),
        ),
    ]
