# Generated by Django 2.0.7 on 2019-09-19 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0019_auto_20190919_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='image',
        ),
    ]
