# Generated by Django 2.0.7 on 2019-09-21 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0020_remove_painting_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paintingphoto',
            options={'ordering': ['src']},
        ),
    ]
