# Generated by Django 2.0.7 on 2019-09-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0022_auto_20190930_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='size_class',
            field=models.CharField(blank=True, choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], default='', max_length=255, null=True),
        ),
    ]
