# Generated by Django 2.0.7 on 2019-09-30 15:46

from django.db import migrations
import paintings.models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0023_auto_20190930_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='artist',
            field=paintings.models.NameField(blank=True, default='', max_length=255, null=True),
        ),
    ]
