# Generated by Django 2.0.7 on 2019-10-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0024_auto_20190930_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='style',
            field=models.CharField(blank=True, choices=[('abstract', 'abstract'), ('animal', 'animal'), ('landscape', 'landscape'), ('nature', 'nature'), ('people', 'people'), ('portrait', 'portrait')], default='', max_length=255, null=True),
        ),
    ]
