# Generated by Django 2.0.7 on 2019-10-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0025_auto_20191001_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='style',
            field=models.CharField(blank=True, choices=[('abstract', 'abstract'), ('animal', 'animal'), ('landscape', 'landscape'), ('nature', 'nature'), ('people', 'people'), ('portrait', 'portrait'), ('other', 'other')], default='', max_length=255, null=True),
        ),
    ]
