# Generated by Django 2.0.7 on 2019-10-13 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0026_auto_20191013_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='series',
        ),
    ]
