# Generated by Django 2.0.7 on 2019-10-13 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0027_remove_painting_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='medium',
        ),
    ]
