# Generated by Django 2.0.7 on 2019-10-13 00:32

from django.db import migrations
import paintings.models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0028_remove_painting_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='artist',
            field=paintings.models.NameField(blank=True, choices=[('brian', 'brian'), ('tracy', 'tracy')], default='', max_length=255, null=True),
        ),
    ]
