# Generated by Django 2.0.7 on 2019-10-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0029_auto_20191013_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='artist',
            field=models.CharField(blank=True, choices=[('brian', 'brian'), ('tracy', 'tracy')], default='', max_length=255, null=True),
        ),
    ]
