# Generated by Django 2.0.7 on 2019-10-13 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paintings', '0030_auto_20191013_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintingphoto',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
