# Generated by Django 2.0.7 on 2019-11-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0031_paintingphoto_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='artist',
            field=models.CharField(blank=True, choices=[('Brian', 'Brian'), ('Tracy', 'Tracy')], default='', max_length=255, null=True),
        ),
    ]
