# Generated by Django 2.0.7 on 2019-11-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0032_auto_20191120_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='medium',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
