# Generated by Django 2.0.7 on 2019-11-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191113_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
