# Generated by Django 2.0.7 on 2019-10-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_cart_session_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='cart',
            name='painting_title_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
