# Generated by Django 2.0.7 on 2019-10-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20191028_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='paintings', to='paintings.Painting'),
        ),
    ]
