# Generated by Django 2.0.7 on 2019-10-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20191029_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='painting_title_slug',
        ),
    ]
